dependencies:
- python >= 3.6
- numpy
- numpydoc
- scipy
- pandas
- cython
- h5py
- pyshp >= 2.3.1
- lxml
- matplotlib >= 3
- sphinx
- sphinx-copybutton
- build
- flake8
- pip
- pip:
    - cdflib
    - hdf5storage >= 0.1.17
    - sphinx-gallery
