name: CI

on:
  workflow_dispatch:
  push:
    branches: [ setup-ci ]
  pull_request:
    branches: [ master ]
  schedule:
    # Weekly on Sunday
    - cron: "0 1 * * 0"

jobs:
  checks:
    name: Check Python ${{ matrix.python-version }} on ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install package
      run: python -m pip install .[full]

    # Tests are not ready to run in CI yet, so just do a basic import test
    - name: Test import
      run: python -c "import chaosmagpy"
